# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: 求人不如求己的部落格
subtitle: "一个用于自嗨自省自嘲的空间，反正也没人爱看"
email: chenyan5@asu.edu
name: Young Li
description: >
  感谢你们在百忙之中光临
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "/myblog" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
# disqus_shortname: bencentra

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: 读后感
    desc: "行万里路，读万卷书"

  - cat: 瞎BB
    desc: "吾三日一省吾身"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social: 

   - name: GitHub
    icon: github
    username: radiump
    url: https://github.com/radiump
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Chenyang Li
    url: https://www.linkedin.com/in/chenyang-young-li-9141a7112/
    desc: Connect with me on LinkedIn
    share: true  

  - name: YouTube
    icon: youtube
    username: 
    url: https://www.youtube.com/channel/UCJR4DCUWG8xecwqEwdkYg5w/featured?view_as=subscriber
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username: @atychip
    url: 
    desc: Follow me on Instagram
    share: true  

  - name: Steam
    icon: steam
    username:
    url: https://steamcommunity.com/id/radiump/
    desc: Friend me on Steam
    share: true

 
# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
